apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-user-app-ingress
  namespace: flask-user-app-dev-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-user-app-service
            port:
              number: 80