apiVersion: v1
kind: Namespace
metadata:
  name: flask-user-app-dev-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-user-app-secret
  namespace: flask-user-app-dev-namespace
stringData:
  DB_PASSWORD: "postgres"